name: test-check

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "^3.8"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install poetry pytest
      - name: Install app
        run: |
          make build
          make install
      - name: Test with pytest
        run: |
          make test
      - name: Test Coverage
        uses: paambaati/codeclimate-action@v5.0.0
        if: github.ref_name == 'main'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
      - name: Lint with flake 8
        run: |
          make lint
